# Generated by Django 6.0.7 on 2026-07-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="depth",
            field=models.PositiveSmallIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Icon identifier for the mega menu, e.g. a lucide-react icon name.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="category.category",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="path",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=800),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["path"], name="category_ca_path_02dc1c_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent", "sort_order"], name="category_ca_parent__e7cb20_idx"),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="unique_category_name_per_parent"
            ),
        ),
    ]
